version: '3.7'

networks:
  proxy:
    external: true

services:

  traefik:
    image: traefik:v2.3
    restart: always
    networks:
      - pterodactyl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR_TRAEFIK}/traefik/traefik.toml:/etc/traefik/traefik.toml
